// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"github.com/google/wire"
	"github.com/weapon-team/weapon/internal/admin/api"
	"github.com/weapon-team/weapon/internal/admin/service"
	"github.com/weapon-team/weapon/internal/sdk/engine"
	"github.com/weapon-team/weapon/internal/sdk/web"
)

// Injectors from wire.go:

// AllAdminRouters 初始化所有路由并返回 []web.IRouter
func AllAdminRouters(deps *engine.Engines) []web.IRouter {
	sysUserService := service.NewSysUserService(deps)
	sysUserApi := api.NewSysUserApi(sysUserService)
	sysUserRouter := NewSysUserRouter(sysUserApi)
	sysRoleApi := api.NewSysRoleApi()
	sysRoleRouter := NewSysRoleRouter(sysRoleApi)
	sysOptionService := service.NewSysOptionService(deps)
	commonApi := api.NewCommonApi(sysOptionService)
	commonRouter := NewCommonRouter(commonApi)
	captchaApi := api.NewCaptchaApi()
	captchaRouter := NewCaptchaRouter(captchaApi)
	v := buildAllIRouter(sysUserRouter, sysRoleRouter, commonRouter, captchaRouter)
	return v
}

// wire.go:

// 所有的Admin service都需要添加到这里
var allAdminService = wire.NewSet(service.NewSysUserService, service.NewSysRoleService, service.NewSysOptionService)

// 所有的Admin api都需要添加到这里
var allAdminApi = wire.NewSet(api.NewSysUserApi, api.NewSysRoleApi, api.NewCaptchaApi, api.NewCommonApi)

// 所有的Admin Router都需要添加到这里
var allAdminRouter = wire.NewSet(
	NewSysUserRouter,
	NewSysRoleRouter,
	NewCommonRouter,
	NewCaptchaRouter,
)

// 每添加一个Router都在这里添加一个参数并返回
func buildAllIRouter(
	userRouter *SysUserRouter,
	roleRouter *SysRoleRouter,
	commonRouter *CommonRouter,
	captchaRouter *CaptchaRouter,
) []web.IRouter {
	return []web.IRouter{
		userRouter,
		roleRouter,
		commonRouter,
		captchaRouter,
	}
}
